on:
  push:
    branches:
      - 'master'

name: Sync beta with master

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          source_ref: ${{ github.ref }}
          target_branch: 'beta'
          commit_message_template: 'chore(ci): merge {source_ref} into target {target_branch}'
